@auth_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImNoYW53aW5oYXJvbGRAZ21haWwuY29tIiwiaWF0IjoxNzg4NjYwNDQ3fQ.WhY94kL-Q2A3fcxZrJVa4isrmOxb0hj7MEPN3lsz36g

### PUT request to toggle the isPublished field
PUT {{apiURL}}/blog/publish
Authorization: {{auth_token}}
Content-Type: application/json

{
    "_id": "6a9f4ee3911046f389d84937"
}

###